{% set name = "powerloader" %}
{% set version = "0.3.0" %}
{% set sha256 = "3d771a857ce39f7090b1d87eca5660bcf784fdc7b7efa601a34550bfe2a97e0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/powerloader/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - powerloader_cmake.patch

build:
  number: 0
  skip: true  # [(win and vc<14) or py==36]

outputs:
  - name: powerloader
    script: build_pl.sh             # [unix]
    script: build_pl.bat            # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - libcurl
        - openssl
        - nlohmann_json
        - cli11
        - zchunk
        - spdlog
        - cpp-expected
        - yaml-cpp
    build:
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}
    test:
      commands:
        - test -d ${PREFIX}/include/powerloader                                                        # [unix]
        - test -f ${PREFIX}/include/powerloader/powerloader.hpp                                        # [unix]
        - test -f ${PREFIX}/lib/cmake/powerloader/powerloaderConfig.cmake                              # [unix]
        - test -f ${PREFIX}/lib/cmake/powerloader/powerloaderConfigVersion.cmake                       # [unix]
        - test -f ${PREFIX}/lib/libpowerloader${SHLIB_EXT}                                             # [unix]
        - test -e ${PREFIX}/bin/powerloader                                                            # [unix]
        - if not exist %LIBRARY_PREFIX%\include\powerloader\powerloader.hpp (exit 1)                   # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\powerloader\powerloaderConfig.cmake (exit 1)         # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\powerloader\powerloaderConfigVersion.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\libpowerloader.lib (exit 1)                                # [win]
        - if not exist %LIBRARY_PREFIX%\bin\libpowerloader.dll (exit 1)                                # [win]
        - if not exist %LIBRARY_PREFIX%\bin\powerloader.exe (exit 1)                                   # [win]

  - name: powerloader-static
    script: build_pl.sh             # [unix]
    script: build_pl.bat            # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - {{ pin_subpackage('powerloader', exact=True) }}
        - libcurl
        - openssl
        - nlohmann_json
        - cli11
        - zchunk
        - spdlog
        - cpp-expected
        - yaml-cpp
    test:
      commands:
        - test -f $PREFIX/lib/libpowerloader.a  # [not win]
        - if not exist %LIBRARY_LIB%\libpowerloader_static.lib exit 1  # [win]


about:
  home: https://github.com/mamba-org/powerloader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A tool to download large files, used in mamba
  description: This is a tool to download large files. This is to be used in mamba and potentially other package managers.
  dev_url: https://github.com/mamba-org/powerloader

extra:
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - wolfv
