{% set name = "powerloader" %}
{% set version = "0.6.0" %}
{% set sha256 = "79c128bdf3f7d2bde191e1513ec9900027d5133a3bd86cf733061233d258ed53 " %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/powerloader/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [(win and vc<14) or py==36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libcurl >=7.88.1
    - libcurl-static >=7.88.1
    - openssl
    - libopenssl-static  # [not win]
    - libnghttp2-static  # [not win]
    - zstd-static        # [not win]
    - libssh2-static     # [not win]
    - krb5-static        # [not win]
    - nlohmann_json
    - zchunk
    - zchunk-static
    - spdlog
    - cpp-expected
    - cli11
    - yaml-cpp
    - zlib  # [unix]

outputs:
  - name: powerloader
    files:
      - bin/powerloader           # [unix]
      - lib/libpowerloader.so     # [linux]
      - lib/libpowerloader.dylib  # [osx]
      - Library\bin\powerloader.exe     # [win]
      - Library\bin\libpowerloader.dll  # [win]
      - Library\lib\libpowerloader.lib  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}
    requirements:
      run:
        - libcurl >=7.88.1
        - openssl
        - zchunk
        - cli11
        - yaml-cpp
    test:
      commands:

        - test -f ${PREFIX}/lib/libpowerloader${SHLIB_EXT}                                             # [unix]
        - test -e ${PREFIX}/bin/powerloader                                                            # [unix]
        - if not exist %LIBRARY_PREFIX%\lib\libpowerloader.lib (exit 1)                                # [win]
        - if not exist %LIBRARY_PREFIX%\bin\libpowerloader.dll (exit 1)                                # [win]
        - if not exist %LIBRARY_PREFIX%\bin\powerloader.exe (exit 1)                                   # [win]

  - name: powerloader-dev
    files:
      - include/powerloader                     # [unix]
      - lib/cmake/powerloader                   # [unix]
      - lib/libpowerloader.a                    # [unix]
      - Library\include\powerloader             # [win]
      - Library\lib\cmake\powerloader           # [win]
     #- Llibrary\lib\libpowerloader_static.lib  # [win]
    requirements:
      run:
        - libcurl-static >=7.88.1
        - libopenssl-static  # [not win]
        - libnghttp2-static  # [not win]
        - zstd-static        # [not win]
        - libssh2-static     # [not win]
        - krb5-static        # [not win]
        - zlib               # [unix]
        - nlohmann_json
        - zchunk-static
        - spdlog
        - cpp-expected
        - {{ pin_subpackage('powerloader', exact=True) }}
    test:
      commands:
        - test -d ${PREFIX}/include/powerloader                                                        # [unix]
        - test -f ${PREFIX}/include/powerloader/powerloader.hpp                                        # [unix]
        - test -f ${PREFIX}/lib/cmake/powerloader/powerloaderConfig.cmake                              # [unix]
        - test -f ${PREFIX}/lib/cmake/powerloader/powerloaderConfigVersion.cmake                       # [unix]
        - test -f $PREFIX/lib/libpowerloader.a                                                         # [unix]
        - if not exist %LIBRARY_PREFIX%\include\powerloader\powerloader.hpp (exit 1)                   # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\powerloader\powerloaderConfig.cmake (exit 1)         # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\powerloader\powerloaderConfigVersion.cmake (exit 1)  # [win]
       #- if not exist %LIBRARY_LIB%\libpowerloader_static.lib exit 1                                  # [win]


about:
  home: https://github.com/mamba-org/powerloader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A tool to download large files, used in mamba
  description: This is a tool to download large files. This is to be used in mamba and potentially other package managers.
  dev_url: https://github.com/mamba-org/powerloader

extra:
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - wolfv
